version: '3.8'
services:
  db:
    image: mysql:latest
    container_name: php_serveur_mysql
    restart: always
    volumes:
      - ./mysql:/var/lib/terresnoires
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: terresnoires
      MYSQL_USER: venture
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_serveur_php
    ports:
      - "8181:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: php_serveur_pma
    ports:
      - "8282:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ''
    depends_on:
      - db
